-- MySQL Script generated by MySQL Workbench
-- Sun Dec 11 08:03:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema` DEFAULT CHARACTER SET utf8 ;
USE `sistema` ;

-- -----------------------------------------------------
-- Table `sistema`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema`.`cliente` ;

CREATE TABLE IF NOT EXISTS `sistema`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `celular_UNIQUE` (`telefone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema`.`veiculo` ;

CREATE TABLE IF NOT EXISTS `sistema`.`veiculo` (
  `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(8) NOT NULL,
  `renavam` VARCHAR(11) NOT NULL,
  `marca` VARCHAR(20) NOT NULL,
  `modelo` VARCHAR(20) NOT NULL,
  `cor` VARCHAR(20) NOT NULL,
  `ano` INT NOT NULL,
  `vendido` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`),
  UNIQUE INDEX `idVeiculo_UNIQUE` (`idVeiculo` ASC) VISIBLE,
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) VISIBLE,
  UNIQUE INDEX `renavam_UNIQUE` (`renavam` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`gerente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema`.`gerente` ;

CREATE TABLE IF NOT EXISTS `sistema`.`gerente` (
  `idGerente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idGerente`),
  UNIQUE INDEX `idGerente_UNIQUE` (`idGerente` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `sistema`.`funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `idGerente` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  UNIQUE INDEX `idFuncionario_UNIQUE` (`idFuncionario` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Funcionario_Gerente1_idx` (`idGerente` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Gerente1`
    FOREIGN KEY (`idGerente`)
    REFERENCES `sistema`.`gerente` (`idGerente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema`.`pagamento` ;

CREATE TABLE IF NOT EXISTS `sistema`.`pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `tipo_pagamento` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPagamento`),
  UNIQUE INDEX `idPagamento_UNIQUE` (`idPagamento` ASC) VISIBLE,
  UNIQUE INDEX `tipo_pagamento_UNIQUE` (`tipo_pagamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema`.`venda` ;

CREATE TABLE IF NOT EXISTS `sistema`.`venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `idFuncionario` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `idVeiculo` INT NOT NULL,
  `idPagamento` INT NOT NULL,
  `data_venda` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idVenda`),
  UNIQUE INDEX `idVenda_UNIQUE` (`idVenda` ASC) VISIBLE,
  INDEX `fk_Venda_Cliente_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Venda_Veiculo1_idx` (`idVeiculo` ASC) VISIBLE,
  INDEX `fk_Venda_Funcionario1_idx` (`idFuncionario` ASC) VISIBLE,
  INDEX `fk_Venda_Pagamento1_idx` (`idPagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `sistema`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Veiculo1`
    FOREIGN KEY (`idVeiculo`)
    REFERENCES `sistema`.`veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `sistema`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Pagamento1`
    FOREIGN KEY (`idPagamento`)
    REFERENCES `sistema`.`pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
